//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaThirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_pizza
    {
        public int orderid { get; set; }
        public int ordernumber { get; set; }
        public int userid { get; set; }
        public string paymentmethod { get; set; }
        public decimal totalamount { get; set; }
    
        public virtual user user { get; set; }
    }
}
