//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaThirst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzaThirstEntities : DbContext
    {
        public PizzaThirstEntities()
            : base("name=PizzaThirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<NonvegPizza> NonvegPizzas { get; set; }
        public virtual DbSet<order_pizza> order_pizza { get; set; }
        public virtual DbSet<pizza> pizzas { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<VegPizza> VegPizzas { get; set; }
        public virtual DbSet<review> reviews { get; set; }
    }
}
